spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: ${uri}
          username: ${username}
          password: ${password}

server:
  port: 8888

management:
  server:
    port: 8889
  endpoints:
    web:
      exposure:
        include: "*"
